name: Python application

# Controls when the workflow will run
on:
  push:
    branches: [ main ]  # Triggers on push to the main branch
  pull_request:
    branches: [ main ]  # Triggers on pull requests to the main branch

# Job definition
jobs:
  build:

    # The type of machine to run on
    runs-on: ubuntu-latest

    # Steps to execute in the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up a Python environment
      with:
        python-version: '3.x'  # Use the latest Python 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        pytest  # Run pytest to execute your tests
